import * as fs from 'node:fs'
import * as path from 'node:path'
import process from 'node:process'

/**
 * Generates the Matter reference from Homebridge's own exports, so the lists
 * cannot drift from what Homebridge actually supports.
 *
 * Mirrors gen.ts, which does the same for HAP services and characteristics
 * using @homebridge/hap-nodejs.
 *
 * Writes:
 *  - src/assets/matter-device-types.json  (rendered per device type, like HAP services)
 *  - src/docs/api/matter-clusters.md      (a flat reference page)
 */

// Housekeeping clusters that every endpoint carries. They are not something a
// plugin sets state on, so listing them against all 26 device types is noise.
const boilerplateClusters = [
  'identify',
  'groups',
  'scenesManagement',
  'descriptor',
]

const generatedNotice = '<!-- This page is generated by scripts/gen-matter.ts - do not edit by hand. -->'

// The attribute a generated example should use as a cluster's "main state".
// A cluster's first attribute is often a capability or config value
// (supportedModes, maxPressure, numberOfPositions), which makes a nonsense
// example - these are the attributes a plugin actually reads and writes.
const exampleAttributeByCluster: Record<string, string> = {
  onOff: 'onOff',
  levelControl: 'currentLevel',
  colorControl: 'colorTemperatureMireds',
  booleanState: 'stateValue',
  temperatureMeasurement: 'measuredValue',
  relativeHumidityMeasurement: 'measuredValue',
  illuminanceMeasurement: 'measuredValue',
  occupancySensing: 'occupancy',
  airQuality: 'airQuality',
  doorLock: 'lockState',
  thermostat: 'occupiedHeatingSetpoint',
  fanControl: 'percentSetting',
  switch: 'currentPosition',
  valveConfigurationAndControl: 'currentState',
  pumpConfigurationAndControl: 'pumpStatus',
  rvcRunMode: 'currentMode',
  rvcCleanMode: 'currentMode',
  rvcOperationalState: 'operationalState',
  windowCovering: 'currentPositionLiftPercent100ths',
  smokeCoAlarm: 'smokeState',
  powerSource: 'batPercentRemaining',
  electricalPowerMeasurement: 'activePower',
  electricalEnergyMeasurement: 'cumulativeEnergyImported',
  bridgedDeviceBasicInformation: 'nodeLabel',
}

// Attributes that are capabilities, limits or configuration rather than state,
// used as a fallback filter for clusters not in the map above.
const nonStateAttribute = /^(?:supported|max|min|abs|default|numberOf|multiPress|featureMap$|clusterRevision$)|List$/

function pickExampleAttribute(clusterId: string, attributes: string[]): string | undefined {
  const preferred = exampleAttributeByCluster[clusterId]
  if (preferred && attributes.includes(preferred)) {
    return preferred
  }
  return attributes.find(a => !nonStateAttribute.test(a)) ?? attributes[0]
}

async function main() {
  const { deviceTypes, clusterNames } = await import('homebridge')

  // cluster id (camelCase, e.g. 'onOff') -> friendly name (e.g. 'OnOff')
  const friendlyByClusterId = new Map<string, string>()
  for (const [friendly, id] of Object.entries(clusterNames)) {
    friendlyByClusterId.set(id as string, friendly)
  }

  const parsed = Object.entries(deviceTypes).map(([name, deviceType]) => {
    const dt = deviceType as any
    const behaviors = dt.behaviors ?? {}

    const clusters = Object.keys(behaviors)
      .filter(id => !boilerplateClusters.includes(id))
      .map((id) => {
        const friendly = friendlyByClusterId.get(id)
        if (!friendly) {
          return null
        }
        const cluster = behaviors[id]?.cluster ?? {}
        const attributes = Object.keys(cluster.attributes ?? {})
        return {
          name: friendly,
          id,
          attributes,
          exampleAttribute: pickExampleAttribute(id, attributes),
          commands: Object.keys(cluster.commands ?? {}),
        }
      })
      .filter((c): c is NonNullable<typeof c> => c !== null)

    return {
      name,
      matterName: dt.name as string,
      deviceTypeId: dt.deviceType as number,
      deviceTypeHex: `0x${(dt.deviceType as number).toString(16).toUpperCase().padStart(4, '0')}`,
      deviceRevision: dt.deviceRevision as number,
      clusters,
    }
  }).sort((a, b) => (a.name > b.name ? 1 : -1))

  fs.writeFileSync(
    path.resolve(import.meta.dirname, '../src/assets/matter-device-types.json'),
    JSON.stringify(parsed, null, 4),
  )

  writeClustersPage(Object.entries(clusterNames).map(([friendly, id]) => ({
    friendly,
    id: id as string,
    usedBy: parsed.filter(d => d.clusters.some(c => c.name === friendly)).map(d => d.name),
  })).sort((a, b) => (a.friendly > b.friendly ? 1 : -1)))

  console.log(`Generated ${parsed.length} Matter device types and ${Object.keys(clusterNames).length} clusters.`)
}

function writeClustersPage(rows: Array<{ friendly: string, id: string, usedBy: string[] }>) {
  const lines = [
    generatedNotice,
    '',
    '# Matter Clusters',
    '',
    'The clusters Homebridge exposes, for use with [`updateAccessoryState()`](api/matter-state#apimatterupdateaccessorystate) and [`getAccessoryState()`](api/matter-state#apimattergetaccessorystate):',
    '',
    '```js',
    'await api.matter.updateAccessoryState(uuid, api.matter.clusterNames.OnOff, { onOff: true });',
    '```',
    '',
    'Prefer `api.matter.clusterNames.OnOff` to the string `\'onOff\'` — the constant is what gives you autocomplete on the cluster and type checking on its attribute names.',
    '',
    'For the attributes and commands each cluster carries, see the device type that uses it under **Matter Device Types**. A cluster with no device types listed is available for [custom device types](api/matter-state#apimatterclusters), but is not part of any of the built-in ones.',
    '',
    '| Name | Value | Used by |',
    '| --- | --- | --- |',
  ]

  for (const row of rows) {
    const usedBy = row.usedBy.length ? row.usedBy.map(d => `\`${d}\``).join(', ') : '—'
    lines.push(`| \`api.matter.clusterNames.${row.friendly}\` | \`${row.id}\` | ${usedBy} |`)
  }

  lines.push('')
  fs.writeFileSync(path.resolve(import.meta.dirname, '../src/docs/api/matter-clusters.md'), lines.join('\n'))
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
